### ISSUE TITLE
"GET" method asks to specify Data and DataMode

### ISSUE THREAD

**Issue by siranov** [jstrausd/ESP8266AsyncHttpClient#1]
![image](https://user-images.githubusercontent.com/97804101/178788908-17eefbeb-bf31-4448-81b8-4a42814cd745.png)

Setting aClient to work with "GET". 

![image](https://user-images.githubusercontent.com/97804101/178788955-63fe01af-f022-4e39-b3ab-56156ffe3ece.png)

Sending request.

![image](https://user-images.githubusercontent.com/97804101/178789098-8d15297e-9c7e-4d36-96e5-4a2026805735.png)

Getting this.

**Comment by jstrausd** [comment]
You have to define the Type before you set the „FullURL“. So the statement with the „GET“ in it, before the setFullURL Statement.

**Comment by LittleBuster** [comment]
```  
if (_dataMode.length() <= 0) {
		Serial.println("DataMode is not defined");
		return;
	}
```
@jstrausd  you don't check if the request is POST , you just exit the function

**Comment by jstrausd** [comment]
Is fixed in the newest version.
